# Generated by Django 2.2.2 on 2020-02-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unnamed', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=2)),
                ('job', models.CharField(max_length=30)),
                ('credit_amount', models.IntegerField(max_length=10)),
                ('duration', models.FloatField(max_length=10)),
                ('purpose', models.CharField(choices=[('C', 'Car'), ('D', 'Domestic'), ('E', 'Education'), ('F', 'Furniture'), ('Ra', 'Radio/TV'), ('Re', 'Repairs'), ('V', 'Vacation/Others')], max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('housing', models.CharField(choices=[('O', 'Own'), ('R', 'Rent')], max_length=1)),
                ('savings', models.CharField(choices=[('M', 'Moderate'), ('N', 'No-Info'), ('Q', 'Quite-Rich'), ('R', 'Rich')], max_length=1)),
                ('risk_bad', models.CharField(max_length=10)),
                ('check', models.CharField(choices=[('M', 'Moderate'), ('N', 'No-Info'), ('R', 'Rich')], max_length=1)),
                ('age_category', models.CharField(choices=[('Y', 'Young'), ('A', 'Adult'), ('S', 'Senior')], max_length=1)),
            ],
        ),
    ]
