# Generated by Django 2.2.2 on 2020-02-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccrecapp', '0004_remove_details_unnamed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='job',
            field=models.CharField(choices=[('N', 'No'), ('B', 'Business'), ('G', 'Government Sector'), ('P', 'Private Sector')], max_length=1),
        ),
    ]
