# Generated by Django 2.2.2 on 2020-02-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccrecapp', '0005_auto_20200212_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='check',
            new_name='checking_account',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='savings',
            new_name='savings_account',
        ),
        migrations.AlterField(
            model_name='details',
            name='risk_bad',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
    ]
